### ISSUE TITLE
problem z formatowaniem "Pytań i odpowiedzi" (faq.md)

### ISSUE THREAD

**Issue by fledgelingt** [tranzycja-pl/tranzycja.pl#115]
# Linia oddzielająca segment "Zabiegi" od segmentu "Terapia Hormonalna" nie pojawia się na stronie, pomimo tego że wyświetla się na githubie.

![image](https://user-images.githubusercontent.com/90787263/147297522-25867a31-0541-47bc-b47a-df626637814b.png)
## Strona

![image](https://user-images.githubusercontent.com/90787263/147297554-b7df7a3f-5504-4b5f-bc1d-90b3da6d3413.png)
## Github

https://github.com/tranzycja-pl/tranzycja.pl/blob/main/source/_ogolne/faq.md

**Comment by Kac-per** [comment]
Błąd był w treści - zauważ, że kreska oddzielająca znajduje się przed znacznikiem zamykającym spoiler, a więc jest wewnątrz niego, co zresztą widać nawet na stronie:

<img width="896" alt="Zrzut ekranu 2022-02-8 o 00 34 05" src="https://user-images.githubusercontent.com/10177632/152890908-0e035ed1-df1e-41a0-9c83-6accb30db91f.png">

Zamiast tego powinna być za zamknięciem spoilera, tak jak wszystkie pozostałe. Na githubie ją widać od razu, ponieważ github nie wyświetla w ogóle spoilerów. Na hackmd jest wszystko prawidłowo, więc po prostu połączyłem na nowo notatkę z plikiem i wszystko już wygląda na stronie jak powinno, zatem zamykam.
