### ISSUE TITLE
Formatowanie górnego indeksu nie wyświetla się poprawnie na stronie

### ISSUE THREAD

**Issue by fledgelingt** [tranzycja-pl/tranzycja.pl#116]
Na hackmd do oznaczenia górnego indeksu używa się znaków dwóch strzałek do góry, co jest wykorzystywane w artykule dotyczącym feminizującej terapii hormonalnej

![image](https://user-images.githubusercontent.com/90787263/147297717-87c032b2-699f-4c7f-86dc-088f782c9fa4.png)

Na githubie i tym samym na stronie przestało wyświetlać się to poprawnie
![image](https://user-images.githubusercontent.com/90787263/147297757-22adb8c1-4c9b-40a5-9973-e7c459837738.png)

https://github.com/tranzycja-pl/tranzycja.pl/blob/main/source/_krok_po_kroku/feminizujaca-terapia-hormonalna.md

**Comment by Kac-per** [comment]
Hackmd wykorzystuje mnóstwo dodatkowych tagów, których nie ma w podstawowej wersji markdowna (którą wykorzystuje github czy strona tranzycji). Indeks górny jest właśnie jedynym z takich tagów. Obsługę części z nich (np. youtube, bloki, spoiler itp) wprowadziłem ręcznie, i teoretycznie mógłbym poświęcić trochę czasu i dodać też ten indeks górny, ale wydaje mi się to niepotrzebne, bo myślę, że można poradzić sobie dużo prościej, stosując np. gwiazdki:

<img width="690" alt="Zrzut ekranu 2022-02-8 o 02 24 43" src="https://user-images.githubusercontent.com/10177632/152901413-26d2c09e-983d-4779-987d-9fb76e9af4fd.png">

Można je normalnie wpisać, co prawda w markdownie gwiazdki służą do formatowania, ale jeśli się ich nie "zamknie", to wtedy wyświetlają się normalnie jako gwiazdki.  
Jedyne newralgiczne miejsce, to przy pojedynczej gwiazdce na początku linijki, ale można dodać tam slash, żeby dać znać markdownowi, żeby nie traktował jej jak znacznika elementu listy, tylko zwykły znak:

<img width="245" alt="Zrzut ekranu 2022-02-8 o 02 27 06" src="https://user-images.githubusercontent.com/10177632/152902082-8889dac7-4157-417f-bde0-1ef8fcb95a14.png">

Co sądzisz o tym, żeby zrobić to gwiazdkami zamiast numerkami?

Dodam jeszcze przy okazji, że przy wpisywaniu jednostek, np. m², też nie trzeba używać indeksu górnego, bo są do tego odpowiednie znaki: ¹²³

**Comment by fledgelingt** [comment]
Używanie gwiazdek może być trochę niezręczne, bo szybko ich liczba może zupełnie rozwalać tabelę, np. przy 4 gwiazdkach ****, ale myślę, że tutaj kłopot rozwiąże to o czym napisałeś na samym końcu, czylli cyferki na sztywno przypisane do indeksu górnego, więc nie ma potrzeby implementować kodu.

**Comment by Kac-per** [comment]
Tylko problem z cyferkami na sztywno przypisanymi do indeksu górnego jest taki, że one zostały stworzone z myślą o jednostkach, więc są to tylko 1, 2 i 3, zatem użycie ich raczej nie wchodzi w grę 😅 No nic, w takim razie muszę jednak dodać obsługę tego znacznika indeksu górnego.

**Comment by kbacia7** [comment]
Nie jestem pewna czy na hackmd też, ale markdown sam w Sobie obsługuje tagi HTML, a w HTMLu jest tag `sup`
`Jakiś tekst<sup>cokolwiek</sup>`

Czy to nie rozwiązuje problemu?
Przykład:
Jakiś tekst<sup>cokolwiek</sup>
