### ISSUE TITLE
Akapity nieoddzielone wolną linijką zlewają się z powrotem w jedną linię

### ISSUE THREAD

**Issue by fledgelingt** [tranzycja-pl/tranzycja.pl#117]
Problem jest obecny zarówno na hackmd, jak i na githubie, nie wiem czy jest to coś możliwego do zmiany, czy wynikającego ze struktury markdowna. Uniemożliwia on wyliczanie rzeczy bez zastosowania oddzielnej linijki, czy punktów

![image](https://user-images.githubusercontent.com/90787263/147297895-3a976426-f22e-49e3-be00-8b4ef2356730.png)
Numery zaufania oddzielone od siebie enterem bez wolnej linijki zlewają się w jednen akapit

![image](https://user-images.githubusercontent.com/90787263/147297953-99a6d4ed-e3ca-4d4c-a5bc-65710aa28ecf.png)
Numery zaufania oddzielone enterem i wolną linijką działają jak trzeba

**Comment by Tash-Feneko** [comment]
Ja bym nie zmieniało działania pojedynczego entera na nową linię, bo w moim odczuciu znacząco nas to oddali od kompatybilności z markdown i może być problematyczne w przyszłości.

Proponuję rozwiązać ten problem dodając:
* listowanie po literkach (tak, wiem, że markdown tego też nie przewiduje, ale jednak zakres użycia będzie ograniczony do konkretnych miejsc)
* opcję zrobienia rozbudowanego przypisu pod tabelą bądź obrazkiem

Chętnie natomiast poznam też opinię programisty :)

**Comment by Kac-per** [comment]
> Chętnie natomiast poznam też opinię programisty :)

**Uwaga, nadchodzi opinia programisty**:  
Zgodnie z tym co zauważa @Tash-Feneko nie zamienianie pojedynczego entera na nową linię jest kompatybilne z githubem (hackmd także przełącza się na takie zachowanie, gdy włączy się synchronizację notatki z githubem) i dlatego na stronie działa to tak samo, żeby nie robić zamętu, jest to celowe.

Mógłbym to zmienić, ale nie miałoby to zbytnio sensu, ponieważ, **UWAGA -  da się zrobić nową linię bez tworzenia nowego akapitu dając dwie spacje przed enterem**. Działa to wszędzie - na hackmd, githubie i na stronie.

Skąd to wiem? Jest to opisane w dokumentacji hackmd: https://hackmd.io/s/link-with-github#Soft-line-breaks

**Comment by fledgelingt** [comment]
Oki, super, ogarnę to w takim razie, dzięki!
