### ISSUE TITLE
Link z brakującym adresem

### ISSUE THREAD

**Issue by ErdaradunGaztea** [tranzycja-pl/tranzycja.pl#137]
Jest w rozdziale "Dysforia płciowa" taki link, który nie prowadzi donikąd, ponieważ brakuje w nim adresu. Nie jestem pewna, jaki miał być ten adres (może rozdział  "Jak poznać, że jestem trans?"?), stąd nie jestem w stanie sama go poprawić.

![image](https://user-images.githubusercontent.com/32573962/156875506-6339ad07-8006-46e5-8b0a-5073c94af2d9.png)

**Comment by fledgelingt** [comment]
Poprawione! Dzięki wielkie za zwrócenie uwagi.
