### ISSUE TITLE
usunięcie cyfr z "krok po kroku"

### ISSUE THREAD

**Issue by fledgelingt** [tranzycja-pl/tranzycja.pl#144]
Tash zasugerowało i ja się zgadzam, by usunąć z "Krok po kroku" cyferki po prawej stronie, tak by nie dawać sugestii, że istnieje tutaj jakakolwiek oficjalna kolejność poszczególnych kroków w ramach tranzycji 

![obraz](https://user-images.githubusercontent.com/90787263/158011111-6c3b7f12-132d-4ecd-bda2-6b378fb5199c.png)

**Comment by Kac-per** [comment]
Zrobione: #146
