### ISSUE TITLE
znaczniki :::info w spojlerach

### ISSUE THREAD

**Issue by fledgelingt** [tranzycja-pl/tranzycja.pl#147]
wyróżnienia części tekstu takie jak :::info, :::danger niepoprawnie wchodzą w interakcję ze spojlerami

![obraz](https://user-images.githubusercontent.com/90787263/159010668-668f7f97-cb6d-4ec1-94f0-b5e1d4b37462.png)

Okienko z numerami telefonu powinno być schowane w spojlerze, ale nie jest. Na hackmd wygląda to w ten sposób:

![obraz](https://user-images.githubusercontent.com/90787263/159010824-b90f4824-c942-4ca5-832c-21dcd33a48d9.png)

![obraz](https://user-images.githubusercontent.com/90787263/159010869-be403c34-c5b3-41b0-ba1f-b2191adecf83.png)

**Comment by fledgelingt** [comment]
jkbc to na razie wrzuciłam też pull request na usunięcie tych znaczników na stronie, więc nie będzie już ich w pliku, ale jako tako myślę że fajnie byloby mieć możliwość umieszczania :::info w spojlerach, więc nadal zostawiam issue

**Comment by Kac-per** [comment]
Mogę prosić o linka do wpisu na hackmd oraz poglądu strony gdzie to występuje?

**Comment by fledgelingt** [comment]
https://hackmd.io/r0B_xkUbQG2sdib_qwEEIA?both
tutaj hackmd

tutaj strona
https://tranzycja.pl/krok-po-kroku/tranzycja-medyczna/

**Comment by Kac-per** [comment]
Kurde, faktycznie coś jest nie tak, muszę poszukać przyczyny i naprawić
