### ISSUE TITLE
W niektórych adresach w slugu dodaje się nbsp

### ISSUE THREAD

**Issue by Tash-Feneko** [tranzycja-pl/tranzycja.pl#156]
Przykład:

https://tranzycja.pl/krok-po-kroku/zmiana-imienia-usc/#czynbsptransplciowosc-lub-niebinarnosc-moga-byc-powodem-zmiany-imienianazwiska

Proszę o naprawienie w taki sposób, aby stare linkowania się nie zepsuły.

**Comment by Kac-per** [comment]
Naprawione #183
